name: Github Pages Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.repository == 'decooio/decoo-cn-wiki'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Install dependencies
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build for production
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Deploy
        uses: hpcodecraft/action-deploy-workspace-to-repo@v2.2
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.DECOO_PAT }}
          SRC_FOLDER: build
          DEST_OWNER: decooio
          DEST_REPO: decoo-cn-wiki-deploy
          DEST_BRANCH: main
          DEST_FOLDER: docs
